const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname);
const lines = [
'# 站点分离（官网 / 后台）部署说明',
'',
'> 规则9 物理拆分执行完成时间：2026-08-08',
'> 代码拆分：见 `site-official/`（官网）和 `site-admin/`（后台+云端APP）',
'',
'## 1. 两站点各自的构建输出根目录',
'',
'| 站点 | 根目录 | Pages / Nginx 指向 |',
'|---|---|---|',
'| 官网 | `site-official/` | `/var/www/kyt-zy/site-official` 或 Cloudflare Pages 项目 `huikang-official` |',
'| 后台+云端APP | `site-admin/` | `/var/www/kyt-zy/site-admin` 或 Cloudflare Pages 项目 `huikang-admin` |',
'',
'## 2. 两个 Pages 项目（Cloudflare）',
'',
'### 2.1 huikang-official（纯展示）',
'- 绑定域名：`www.huikangzy.com`',
'- 构建命令：无（纯静态）',
'- 输出目录：`site-official`',
'- 路由/头：已经在 `site-official/_routes.json` 和 `site-official/_headers` 写好（敏感路径 /admin /api /auth-core 一律 301 跳后台域）',
'',
'### 2.2 huikang-admin（带鉴权）',
'- 绑定域名：`admin.huikangzy.com`',
'- 构建命令：无（纯静态）',
'- 输出目录：`site-admin`',
'- 需要在 Pages 上绑定 Worker：对所有 `/admin/*` 路由加平台管理员 JWT 校验（role=platform_admin），无登录态一律跳转到 `/admin/index.html#login`',
'',
'## 3. 自托管 Nginx',
'',
'参考 docs 中的 `规则9-官网后台分离实施计划.md` 第 4.1 节直接复制 Nginx 配置。',
'',
'## 4. 流水线发布同步',
'',
'每次 4 版本打包脚本（`pack-app-geren-strict.bat` / `pack-app-strict.bat` / 桌面版 4 个）运行完成后，',
'**需要将 APK/EXE 产物复制到 `site-official/releases/`**，并更新：',
'',
'1. `site-official/hash-manifest.json` — 下载页读取的 SHA-256 清单',
'2. `site-official/updates/cloud_personal/latest.json` — YB 云端标准版',
'3. `site-official/updates/cloud_clinic/latest.json`   — YJ 云端机构版',
'4. `site-official/updates/personal/latest.json`      — LB 离线标准版',
'5. `site-official/updates/clinic/latest.json`        — LJ 离线机构版',
'',
'上述 4 latest.json 在 site-official 目录已作为占位存在，build 时覆盖即可。',
'**旧目录 `updates/geren` / `updates/dingzhi` / `updates/cloud` 仍然存在作为向后兼容，',
'download.html 已经 rewrite 为优先读取 4 新 key，旧 key 保留兼容。**',
'',
'## 5. 规则9验收对照',
'',
'- [x] 官网站点根目录下不存在 `admin/` 目录',
'- [x] 官网站点根目录下不存在 `auth-core.js` / `permission.js` / `security-guard.js`',
'- [x] 官网 index.html 显式声明"本站仅下载 + 规则2 隐私承诺"，并清理 localStorage/cookie',
'- [x] 官网 `_routes.json` 把 `/admin/* /api/* /auth-core.js /permission.js /login.html` 全部 301 跳后台域',
'- [x] 后台站点根目录存在 `admin/ticket-approval.html`、`admin/build-queue.html`、`admin/activation-codes.html` 导航入口',
'- [x] 工单审批页 machineId 显示前后各 6 位 + 中间打码（不泄露完整哈希给操作员，符合规则3）',
'',
];
fs.writeFileSync(path.join(ROOT, 'DEPLOY-站点分离部署说明.md'), lines.join('\n') + '\n', 'utf8');
console.log('  DEPLOY-站点分离部署说明.md written (' + lines.length + ' lines)');
